//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.item
{ 

public sealed partial class MyItem :  Bright.Config.BeanBase 
{
    public MyItem(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        PostInit();
    }

    public MyItem(int id ) 
    {
        this.Id = id;
        PostInit();
    }

    public static MyItem DeserializeMyItem(JSONNode _json)
    {
        return new item.MyItem(_json);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }

    public const int __ID__ = -2004594118;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
