//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.item
{ 

public sealed partial class UIForm :  Bright.Config.BeanBase 
{
    public UIForm(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["path"].IsString) { throw new SerializationException(); }  Path = _json["path"]; }
        { if(!_json["group"].IsString) { throw new SerializationException(); }  Group = _json["group"]; }
        PostInit();
    }

    public UIForm(int id, string name, string path, string group ) 
    {
        this.Id = id;
        this.Name = name;
        this.Path = path;
        this.Group = group;
        PostInit();
    }

    public static UIForm DeserializeUIForm(JSONNode _json)
    {
        return new item.UIForm(_json);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 地址
    /// </summary>
    public string Path { get; private set; }
    /// <summary>
    /// UI分组
    /// </summary>
    public string Group { get; private set; }

    public const int __ID__ = -1819983693;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Path:" + Path + ","
        + "Group:" + Group + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
